### PR TITLE
Fixed typing errors and doc enhancement

### PR DESCRIPTION
**Pull request by FarukhS52**
### Description
Fixed some typing errors and grammar enhancements

### CODE REVIEW

**Review by Jwilliamsr — APPROVED** [review]
Approved–Thank you for making these corrections

**Review by amisevsk — APPROVED** [review]

**Comment by bmicklea** [comment]
Thanks @FarukhS52 for the edits, its much appreciated. Did you do this as part of Hacktoberfest? Or just because you noticed the issues?

**Comment by FarukhS52** [comment]
@bmicklea , yes i am participating in hacktoberbest. I am not good in solving issues in codes so i decided to contributing via docs

**Comment by bmicklea** [comment]
Great! We appreciate all contributions. Did you create an issue for this? We need an issue so we can apply the right labels and you can get credit from Hacktoberfest.

**Comment by FarukhS52** [comment]
No i did not create an issue. Sorry
Wasn't aware of that

**Comment by bmicklea** [comment]
No problem, I created and labelled it but you'll need to assign it to yourself (I can't assign it to you):
https://github.com/jozu-ai/kitops/issues/522

**Pull request merged**
