### PR TITLE
feat: added parameters field to datasets and code

### LINKED ISSUE #478: Add parameters field to datasets and code
**Describe the problem you're trying to solve**
The `model` section of a Kitfile contains the parameters field for free-form additional data, to be consumed by other tooling. Such a field would be useful within datasets and code sections as well.

### PR DESCRIPTION
**Pull request by RS-labhub**
Added a kitfile manifest/config file that kit CLI uses to package AI/ML artifacts for `model` -> `datasets` section of the kitfile.

### Linked issues
Fixes #478

### CODE REVIEW

**Comment by RS-labhub** [comment]
@gorkem @javisperez you can review it now!

**Comment by javisperez** [comment]
@amisevsk i think he meant you :)

**Comment by RS-labhub** [comment]
> @amisevsk i think he meant you :)

Ops, yes!! Sorry sorrryyyyy!

**Review by amisevsk — APPROVED** [review]
LGTM, thanks for the contribution!

**Review by gorkem — APPROVED** [review]

**Comment by RS-labhub** [comment]
@gorkem @amisevsk you forgot to add `hacktoberfest` and `hacktoberfest-accepted` labels

**Comment by Jwilliamsr** [comment]
@RS-labhub added

**Pull request merged**
