### PR TITLE
Update CODE-OF-CONDUCT.md

### PR DESCRIPTION
**Pull request by nayan135**
## Key Changes and Additions:

1. **Expanded Scope**: Covers participant behavior beyond official spaces.
2. **Encouraged Behavior**: Highlights empathy, openness to feedback, and collaboration.
3. **Restorative Actions**: Adds non-punitive options like education or mediation.
4. **Consequences of Misconduct**: Lists actions maintainers can take, depending on the violation.
5. **Reporting and Resolution**: Clarifies timelines and handling of reports.

### CODE REVIEW

**Review by NAYAN1357 — APPROVED** [review]

**Comment by gorkem** [comment]
I do not see a lot of value on these changes, besides code of conduct already got its hacktoberfest haircut this year :) It is a -1 for me but WDYT @bmicklea

**Review by amisevsk — CHANGES_REQUESTED** [review]
If you think the code of conduct should be updated, please file an issue first so we can discuss.

**Comment by bmicklea** [comment]
Agreed, I'm not seeing changes here that go much beyond stylistic. Start with an issue that explains what's wrong with the doc as-is and what changes you think should be prioritized.

**Review by bmicklea — CHANGES_REQUESTED** [review]
Needs more detail (in the form of an issue) explaining why the change is necessary / beneficial.

**Comment by gorkem** [comment]
Closing as this does not seem to be relevant

**Pull request closed without merging**
